import type { Metadata } from "next";
import Link from "next/link";
import localFont from "next/font/local";
import "./globals.css";
import { Menubar, MenubarMenu, MenubarTrigger } from "@/components/ui/menubar";
import { Button } from "@/components/ui/button";
import { ThemeProvider } from "@/components/theme-provider";
import dynamic from "next/dynamic";
import { MenubarContent } from "@radix-ui/react-menubar";

const ChangeThemeMode = dynamic(() => import("@/components/ChangeThemeMode"), {
  ssr: false,
});

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-screen`}
      >
        <ThemeProvider attribute="class" defaultTheme="light" enableSystem>
          <div className="flex flex-col h-full">
            <Menubar>
              <MenubarMenu>
                <MenubarTrigger>
                  <Link href={"/"}>Home</Link>
                </MenubarTrigger>
              </MenubarMenu>
              <MenubarMenu>
                <MenubarTrigger>
                  <Link href={"/schedule"}>Matérias</Link>
                </MenubarTrigger>
              </MenubarMenu>
              <MenubarMenu>
                <MenubarTrigger>
                  <Link href={"/professors"}>Professores</Link>
                </MenubarTrigger>
              </MenubarMenu>
              <MenubarMenu>
                <MenubarTrigger>
                  <ChangeThemeMode />
                </MenubarTrigger>
              </MenubarMenu>
            </Menubar>
            <div className="flex-grow h-full">{children}</div>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
