import type { Metadata } from "next";
import Link from "next/link";
import localFont from "next/font/local";
import "./globals.css";
import { Menubar, MenubarMenu, MenubarTrigger } from "@/components/ui/menubar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-screen`}
      >
        <div className="flex flex-col h-full">
          <Menubar>
            <MenubarMenu>
              <MenubarTrigger className="cursor-pointer hover:bg-gray-200">
                <Link href={"/"}>Home</Link>
              </MenubarTrigger>
            </MenubarMenu>
            <MenubarMenu>
              <MenubarTrigger className="cursor-pointer hover:bg-gray-200">
                <Link href={"/schedule"}>Matérias</Link>
              </MenubarTrigger>
            </MenubarMenu>
            <MenubarMenu>
              <MenubarTrigger className="cursor-pointer hover:bg-gray-200">
                Professores
              </MenubarTrigger>
            </MenubarMenu>
          </Menubar>
          <div className="bg-[#f8f8f8] flex-grow h-full">{children}</div>
        </div>
      </body>
    </html>
  );
}
